### ISSUE TITLE
Prototype for BTIOSS

### ISSUE THREAD

**Issue by Abhishah16** [BTIOSS/BTIOSS.github.io#1]
create a index.html

**Comment by yozaam** [comment]
Hi let me do this

**Comment by yozaam** [comment]
https://tailwindcss.com/ can we use this library?

**Comment by Abhishah16** [comment]
> https://tailwindcss.com/ can we use this library?

This is amazing use this for each and every contributor.!!

**Comment by urmilshroff** [comment]
Hey guys, what's this about?

**Comment by yozaam** [comment]
Hey @urmilshroff we want to allow everyone to collaborate and work on some projects, so it's easier to learn for beginners, by watching and solving small bugs
